controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr: '/fr'
        ja: '/ja'
        zh-hans: '/zh-hans'
        pt-br: '/pt-br'
        hu: '/hu'
        es: '/es'
        de: '/de'
        ar: '/ar'
        en: '' # safety net: this is last to ensure a URL containing a locale is not considered as a parameter for an English route

kernel:
    resource: ../../src/Kernel.php
    type: annotation
